### ISSUE TITLE
How can we use api in command

### ISSUE THREAD

**Issue by JackSunjm** [CSC207-UofT/course-project-codemonkeys#65]
The Yahoo finance API is needed for commands such as check price, buy and sell, upvote and downvote.
How can we get the API or can we create a YahooFinaceApi instance in command?

**Comment by a663E-36z1120** [comment]
Yes, we need to instantiate an YahooFinaceStockAPI object in the Interfaces package in order to fetch price in real time. YahooFinaceStockAPI implements the DataAccessInterface class, which enforces that it implements an update() method. You use the update() method by passing the symbol of the stock you want to check the price for. For example:

YahooFinaceStockAPI source = new YahooFinaceStockAPI;
System.out.println(source.update("TSLA"));

This should print the price of 1 tesla stock.

**Comment by langsonzhang** [comment]
👍
